#version 460 core

#include "Core/ShaderCore.glsl"

#include "ShaderDefines.h"
#include "ShaderStructs.h"

FStructuredBuffer(FVisibility,TriangleBuffer,TRIANGLE_VISIBILITY_BUFFER_SLOT)
FStructuredBuffer(FMesh,MeshBuffer,MESH_BUFFER_SLOT)

layout(binding = U_TRI_ID_BINDING) uniform isampler2D u_TriangleID;

NUM_THREADS(NUM_LOCAL_THREAD_X,NUM_LOCAL_THREAD_Y,NUM_LOCAL_THREAD_Z)
void main()
{				
	ivec2 ID = texelFetch(u_TriangleID,  ivec2(gl_GlobalInvocationID.xy), 0).rg;
	if(ID.x != 0 && ID.y != 0)
	{
		int TriangleID = GetMeshBuffer(ID.x - 1).GlobalTriOffset + (ID.y - 1);

		FVisibility Vis;
		Vis.Visibility = VISIBLE;

		// mark triangle as visible
		SetTriangleBuffer(TriangleID,Vis);
	}
}