#ifndef SHADER_DEFINES_H
#define SHADER_DEFINES_H

#define TRIANGLE_VISIBILITY_BUFFER_SLOT 0
#define MESH_BUFFER_SLOT 1

#define INVISIBLE -1
#define VISIBLE 1

#define NUM_LOCAL_THREAD_X 32
#define NUM_LOCAL_THREAD_Y 32
#define NUM_LOCAL_THREAD_Z 1

#define U_TRI_ID_BINDING 0

#endif
