#define MAX_STATIC_MESH_NUM 2048 * 4
#define MAX_INSTANCE_NUM 2048 * 4
#define MAX_INDEX_PER_DRAW 16 * 1024 * 1024 /*400w*/

#define MAX_DEBUG_NUM 10000

/*
	slots
*/
#define POS_SLOT 0
#define INDEX_SLOT 1
#define STATIC_MESH_SLOT 2
#define SCENE_INSTANCE_SLOT 3
#define CULL_PARAM_SLOT 4
#define VISIBLE_INSTANCE_SLOT 5
#define DYNAMIC_INDEX_SLOT 6
#define DRAW_COMMAND_SLOT 7
#define DRAW_DYNAMIC_IBO_COMMAND_SLOT 8
#define STAT_SLOT 9

#define DEBUG_0_SLOT 10
#define DEBUG_1_SLOT 11
