#version 460 core

#include "Core/ShaderCore.glsl"
#include "ShaderDefines.h"
#include "ShaderStructs.h"

FStructuredBuffer(FNCCContext,NCCResult,NCC_RESULT_SLOT)

void AtomicAdd_T_Mul_I_Sum(vec4 data)
{
	// wait for thread lock 0
	while(NCCResultPackedData[0].Lock0 == 1){}

	// lock
	atomicExchange(NCCResultPackedData[0].Lock0,1);

	NCCResultPackedData[0].T_Mul_I_Sum = NCCResultPackedData[0].T_Mul_I_Sum + data;

	// unlock
	atomicExchange(NCCResultPackedData[0].Lock0,0);
}

void AtomicAdd_T_2_Sum(vec4 data)
{
	// wait for thread lock 0
	while(NCCResultPackedData[0].Lock1 == 1){}

	// lock
	atomicExchange(NCCResultPackedData[0].Lock1,1);

	NCCResultPackedData[0].T_2_Sum = NCCResultPackedData[0].T_2_Sum + data;

	// unlock
	atomicExchange(NCCResultPackedData[0].Lock1,0);
}

void AtomicAdd_I_2_Sum(vec4 data)
{
	// wait for thread lock 0
	while(NCCResultPackedData[0].Lock2 == 1){}

	// lock
	atomicExchange(NCCResultPackedData[0].Lock2,1);

	NCCResultPackedData[0].I_2_Sum = NCCResultPackedData[0].I_2_Sum + data;

	// unlock
	atomicExchange(NCCResultPackedData[0].Lock2,0);
}

layout (binding = 0,rgba32f) uniform readonly image2D Template;
layout (binding = 1,rgba32f) uniform readonly image2D Target;

// Each thread group process one image block
NUM_THREADS(BLOCK_SIZE_X,BLOCK_SIZE_Y,1)
void main()
{
//	uvec2 BlockID = gl_WorkGroupID.xy;
//	uvec2 PixelOffset = gl_LocalInvocationID.xy;
//
//	ivec2 UV = ivec2(BlockID.x * BLOCK_SIZE_X + PixelOffset.x,BlockID.y * BLOCK_SIZE_Y + PixelOffset.y);
//
//	vec4 T_0 = imageLoad(Template,UV);
//	vec4 I_0 = imageLoad(Target,UV);

//	AtomicAdd_T_Mul_I_Sum(T_0*I_0);
//	AtomicAdd_T_2_Sum(T_0*T_0);
//	AtomicAdd_I_2_Sum(I_0*I_0);

//	barrier();

//	if(GLOBAL_THREAD_ID_1D == 0)
//	{
//		NCCResultPackedData[0].Result = NCCResultPackedData[0].T_Mul_I_Sum/(NCCResultPackedData[0].T_2_Sum*NCCResultPackedData[0].I_2_Sum);
//	}
}