/*
	function:make target image a zero-average image
*/
#version 460 core

#include "Core/ShaderCore.glsl"
#include "ShaderDefines.h"
#include "ShaderStructs.h"

layout (binding = 0,rgba32f) uniform image2D TargetTex;

// Saved Block Data
shared vec4 PixelData[BLOCK_SIZE_X][BLOCK_SIZE_Y];
shared vec4 Average;

// Each thread group process one image block
NUM_THREADS(BLOCK_SIZE_X,BLOCK_SIZE_Y,1)
void main()
{    
	uvec2 BlockID = gl_WorkGroupID.xy;
	uvec2 PixelOffset = gl_LocalInvocationID.xy;

	ivec2 TargetTexUV = ivec2(BlockID.x * BLOCK_SIZE_X + PixelOffset.x,BlockID.y * BLOCK_SIZE_Y + PixelOffset.y);

	// copy block data
	PixelData[PixelOffset.x][PixelOffset.y] = imageLoad(TargetTex,TargetTexUV);

	barrier();

	// calculate block average
	if (LOCAL_THREAD_ID_1D == 0) 
    {
		int i,j;

		for(i = 0 ;i < BLOCK_SIZE_X; ++i)
		{
			for(j = 0 ;j < BLOCK_SIZE_Y; ++j)
			{
				Average += PixelData[i][j];
			}
		}

		Average /= vec4(BLOCK_SIZE,BLOCK_SIZE,BLOCK_SIZE,BLOCK_SIZE);
	}

	barrier();

	// restore image data
	imageStore(TargetTex,TargetTexUV,PixelData[PixelOffset.x][PixelOffset.y] - Average);
}