#ifndef SHADER_DEFINES_H
#define SHADER_DEFINES_H

#define VERTEX_BUFFER_SLOT 0
#define TRIANGLE_BUFFER_SLOT 1
#define MESH_BUFFER_SLOT 2
#define SCENE_BUFFER_SLOT 3
#define TRIANGLE_COLLECTION_BUFFER_SLOT 4
#define TRIANGLE_COLLECTION_PROFILING_SLOT 5

#define DEBUG_SLOT TRIANGLE_COLLECTION_PROFILING_SLOT + 1


#endif
